# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/nate/projects/duneWireTension/vivadoProjects/cores/cores.srcs/sources_1/ip/xadc_senseWire/xadc_senseWire.xci
# IP: The module: 'xadc_senseWire' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/nate/projects/duneWireTension/vivadoProjects/cores/cores.srcs/sources_1/ip/xadc_senseWire/xadc_senseWire_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'xadc_senseWire'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/nate/projects/duneWireTension/vivadoProjects/cores/cores.srcs/sources_1/ip/xadc_senseWire/xadc_senseWire.xdc
# XDC: The top module name and the constraint reference have the same name: 'xadc_senseWire'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/nate/projects/duneWireTension/vivadoProjects/cores/cores.srcs/sources_1/ip/xadc_senseWire/xadc_senseWire.xci
# IP: The module: 'xadc_senseWire' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/nate/projects/duneWireTension/vivadoProjects/cores/cores.srcs/sources_1/ip/xadc_senseWire/xadc_senseWire_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'xadc_senseWire'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/nate/projects/duneWireTension/vivadoProjects/cores/cores.srcs/sources_1/ip/xadc_senseWire/xadc_senseWire.xdc
# XDC: The top module name and the constraint reference have the same name: 'xadc_senseWire'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
