# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/nate/projects/duneWireTension/vivadoProjects/cores/cores.srcs/sources_1/ip/ila_xadc/ila_xadc.xci
# IP: The module: 'ila_xadc' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/nate/projects/duneWireTension/vivadoProjects/cores/cores.srcs/sources_1/ip/ila_xadc/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_xadc'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/nate/projects/duneWireTension/vivadoProjects/cores/cores.srcs/sources_1/ip/ila_xadc/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_xadc'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/nate/projects/duneWireTension/vivadoProjects/cores/cores.srcs/sources_1/ip/ila_xadc/ila_xadc_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_xadc'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/nate/projects/duneWireTension/vivadoProjects/cores/cores.srcs/sources_1/ip/ila_xadc/ila_xadc.xci
# IP: The module: 'ila_xadc' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/nate/projects/duneWireTension/vivadoProjects/cores/cores.srcs/sources_1/ip/ila_xadc/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_xadc'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/nate/projects/duneWireTension/vivadoProjects/cores/cores.srcs/sources_1/ip/ila_xadc/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_xadc'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/nate/projects/duneWireTension/vivadoProjects/cores/cores.srcs/sources_1/ip/ila_xadc/ila_xadc_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_xadc'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
